# Generated by Django 2.0 on 2019-11-08 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avion',
            fields=[
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('modelo', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('kilometraje', models.IntegerField()),
                ('nuevo', models.BooleanField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('modelo', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('kilometraje', models.IntegerField()),
                ('nuevo', models.BooleanField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
